name: Publish Buildarr installer

on:
  release:
    types:
      - published

jobs:
  buildarr-installer:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Update package metadata
        run: sudo apt-get update
      - name: Install system packages
        run: sudo apt-get install -y make nsis
      - name: Install pynsist
        run: python -m pip install pynsist
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Build Buildarr installer
        run: make
      - name: Upload Buildarr installer to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/nsis/buildarr-installer-*.exe
          release_id: ${{ github.event.release.id }}
          overwrite: true
