name: Publish Buildarr installer

on:
  release:
    types:
      - published

jobs:
  wheels:
    runs-on: windows-2022
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Download and build wheels
        run: python -m pip wheel --requirement requirements.txt --wheel-dir wheels
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels
          retention-days: 5

  buildarr-installer:
    needs: wheels
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Update package metadata
        run: sudo apt-get update
      - name: Install system packages
        run: sudo apt-get install -y nsis
      - name: Install pynsist
        run: python -m pip install pynsist==2.8
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Download wheels from build artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheels
      - name: Build Buildarr installer
        run: pynsist installer.cfg
      - name: Upload Buildarr installer to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/nsis/buildarr-installer-*.exe
          release_id: ${{ github.event.release.id }}
          overwrite: true
