name: Test Buildarr installer build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildarr-installer:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Update package metadata
        run: sudo apt-get update
      - name: Install system packages
        run: sudo apt-get install -y make nsis
      - name: Install pynsist
        run: python -m pip install pynsist
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Build Buildarr installer
        run: make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buildarr-installer
          path: build/nsis
          retention-days: 5
