name: Test Buildarr installer build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  wheels:
    runs-on: windows-2022
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Download and build wheels
        run: python -m pip wheel --requirement requirements.txt --wheel-dir wheels
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels
          retention-days: 5

  buildarr-installer:
    needs: wheels
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Update package metadata
        run: sudo apt-get update
      - name: Install system packages
        run: sudo apt-get install -y nsis zip
      - name: Install pynsist
        run: python -m pip install pynsist==2.8
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Download wheels from build artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheels
      - name: Build Buildarr installer
        run: pynsist installer.cfg
      - name: Compress package build artifacts
        run: zip -r pkgs.zip pkgs
        working-directory: build/nsis
      - name: Compress Python build artifacts
        run: zip -r Python.zip Python
        working-directory: build/nsis
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buildarr-installer
          path: |
            build/nsis/bin
            build/nsis/*.exe
            build/nsis/*.ico
            build/nsis/*.py[w]
            build/nsis/installer.nsi
            build/nsis/LICENSE.txt
            build/nsis/pkgs.zip
            build/nsis/Python.zip
            build/nsis/_system_path.py
          retention-days: 5
